schema_version: 1

context:
  name: python_jsonschema_objects
  version: 0.5.7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/python_jsonschema_objects-${{ version }}.tar.gz
  sha256: 0af1a9fd207a3158a73baa895256ce0ee91bb99c5f92b07fd4fac6ff6d007c90

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=18.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - inflection >=0.2
    - markdown >=2.4
    - jsonschema >=4.18
    - six >=1.5.2

tests:
  - python:
      imports:
        - python_jsonschema_objects
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: An object wrapper for JSON Schema definitions
  license: MIT
  license_file: LICENSE
  homepage: http://python-jsonschema-objects.readthedocs.org/

extra:
  recipe-maintainers:
    - jan-janssen
